name: dear_days
description: A professional personal diary app built with Flutter.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  table_calendar: ^3.0.9
  intl: ^0.20.2

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2

  # Firebase
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
