name: dear_days
description: A professional personal diary app built with Flutter.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_staggered_animations: ^1.1.1 
  photo_view: ^0.15.0
  table_calendar: ^3.2.0
  intl: ^0.20.2 
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  path: ^1.9.0 
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.2.3
  sqflite: ^2.3.2
  firebase_core: ^4.0.0
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^6.0.0
 

  
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
